import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";

import { triggerDownload } from "@/lib/reports/csv";
import type { ReportPayload } from "@/lib/reports/types";

function cell(text: string, opts?: { bold?: boolean; fill?: string; width?: number }) {
  return new TableCell({
    width: { size: opts?.width ?? 1500, type: WidthType.DXA },
    shading: opts?.fill ? { fill: opts.fill } : undefined,
    borders: {
      top: { style: BorderStyle.SINGLE, size: 4, color: "0F4628" },
      bottom: { style: BorderStyle.SINGLE, size: 4, color: "0F4628" },
      left: { style: BorderStyle.SINGLE, size: 4, color: "0F4628" },
      right: { style: BorderStyle.SINGLE, size: 4, color: "0F4628" },
    },
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text,
            bold: opts?.bold,
            font: "Times New Roman",
            size: 16,
          }),
        ],
      }),
    ],
  });
}

export async function downloadGovDocx(payload: ReportPayload) {
  const asOn = (payload.meta.asOn ?? new Date()).toLocaleDateString("en-GB");
  const colCount = Math.max(payload.table.columns.length, 1);
  const colWidth = Math.floor(9000 / colCount);

  const headerRow = new TableRow({
    children: payload.table.columns.map((c) =>
      cell(c.header, { bold: true, fill: "DCEFE4", width: colWidth }),
    ),
  });

  const bodyRows = payload.table.rows.map(
    (row) =>
      new TableRow({
        children: payload.table.columns.map((c) =>
          cell(String(row[c.key] ?? ""), { width: colWidth }),
        ),
      }),
  );

  const summaryParas =
    payload.summaryLines?.map(
      (s) =>
        new Paragraph({
          children: [
            new TextRun({ text: `${s.label}: `, bold: true, font: "Times New Roman", size: 20 }),
            new TextRun({ text: s.value, font: "Times New Roman", size: 20 }),
          ],
        }),
    ) ?? [];

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            size: { orientation: "landscape" },
          },
        },
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: "GOVERNMENT OF THE PUNJAB",
                bold: true,
                font: "Times New Roman",
                size: 28,
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: "EVACUEE TRUST PROPERTY BOARD (ETPB)",
                bold: true,
                font: "Times New Roman",
                size: 24,
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
            children: [
              new TextRun({
                text: "Legal Case Management System — Official Report",
                font: "Times New Roman",
                size: 20,
                italics: true,
              }),
            ],
          }),
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: payload.meta.title,
                bold: true,
                font: "Times New Roman",
                size: 24,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Office / Court: ${payload.meta.officeOrCourt || "ETPB / IPS Legal Wing"}`,
                font: "Times New Roman",
                size: 18,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `File Ref: ${payload.meta.fileRef || "ETPB/LGL/CRM/RPT"}  |  As on: ${asOn}`,
                font: "Times New Roman",
                size: 18,
              }),
            ],
          }),
          new Paragraph({
            spacing: { after: 200 },
            children: [
              new TextRun({
                text: `Generated by: ${payload.meta.generatedBy}${payload.meta.generatedRole ? ` (${payload.meta.generatedRole})` : ""}  |  ${payload.meta.classification || "For Official Use Only"}`,
                font: "Times New Roman",
                size: 18,
              }),
            ],
          }),
          ...summaryParas,
          new Paragraph({ text: "" }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [headerRow, ...bodyRows],
          }),
          new Paragraph({
            spacing: { before: 300 },
            children: [
              new TextRun({
                text: "Prepared through ETPB Legal CRM. Not a certified copy unless signed by an authorised officer.",
                italics: true,
                font: "Times New Roman",
                size: 16,
              }),
            ],
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  triggerDownload(blob, `${payload.fileBaseName}.docx`);
}
