import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import type { ReportPayload } from "@/lib/reports/types";

function formatAsOn(date: Date) {
  const d = date.getDate().toString().padStart(2, "0");
  const m = (date.getMonth() + 1).toString().padStart(2, "0");
  const y = date.getFullYear();
  return `${d}-${m}-${y}`;
}

/**
 * Government of the Punjab / ETPB formal register PDF.
 * Landscape A4 for wide legal registers.
 */
export function downloadGovPdf(payload: ReportPayload) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 12;
  let y = 12;

  doc.setDrawColor(15, 70, 40);
  doc.setLineWidth(0.6);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 6;

  doc.setFont("times", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 55, 30);
  doc.text("GOVERNMENT OF THE PUNJAB", pageWidth / 2, y, { align: "center" });
  y += 6;

  doc.setFontSize(12);
  doc.text("EVACUEE TRUST PROPERTY BOARD (ETPB)", pageWidth / 2, y, { align: "center" });
  y += 5;

  doc.setFont("times", "normal");
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  doc.text("Legal Case Management System — Official Report", pageWidth / 2, y, { align: "center" });
  y += 4;

  doc.setDrawColor(15, 70, 40);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 7;

  doc.setFont("times", "bold");
  doc.setFontSize(11);
  doc.text(payload.meta.title.toUpperCase(), pageWidth / 2, y, { align: "center" });
  y += 6;

  doc.setFont("times", "normal");
  doc.setFontSize(9);
  const asOn = formatAsOn(payload.meta.asOn ?? new Date());
  const metaLeft = [
    `Office / Court: ${payload.meta.officeOrCourt || "ETPB / IPS Legal Wing"}`,
    `File Ref: ${payload.meta.fileRef || "ETPB/LGL/CRM/RPT"}`,
    `Generated by: ${payload.meta.generatedBy}${payload.meta.generatedRole ? ` (${payload.meta.generatedRole})` : ""}`,
  ];
  const metaRight = [
    `As on: ${asOn}`,
    `Classification: ${payload.meta.classification || "For Official Use Only"}`,
    `Records: ${payload.table.rows.length}`,
  ];

  metaLeft.forEach((line, i) => {
    doc.text(line, marginX, y + i * 4.2);
    doc.text(metaRight[i] || "", pageWidth - marginX, y + i * 4.2, { align: "right" });
  });
  y += 16;

  if (payload.summaryLines?.length) {
    doc.setFont("times", "bold");
    doc.setFontSize(9);
    doc.text("Summary position", marginX, y);
    y += 4;
    doc.setFont("times", "normal");
    payload.summaryLines.forEach((item, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = marginX + col * ((pageWidth - marginX * 2) / 3);
      doc.text(`${item.label}: ${item.value}`, x, y + row * 4.2);
    });
    y += Math.ceil(payload.summaryLines.length / 3) * 4.2 + 4;
  }

  const head = [payload.table.columns.map((c) => c.header)];
  const body = payload.table.rows.map((row) =>
    payload.table.columns.map((col) => String(row[col.key] ?? "")),
  );

  autoTable(doc, {
    startY: y,
    head,
    body,
    theme: "grid",
    styles: {
      font: "times",
      fontSize: 7.5,
      cellPadding: 1.4,
      valign: "middle",
      textColor: [30, 30, 30],
      lineColor: [80, 110, 90],
      lineWidth: 0.15,
    },
    headStyles: {
      fillColor: [15, 70, 40],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center",
    },
    alternateRowStyles: {
      fillColor: [245, 250, 247],
    },
    margin: { left: marginX, right: marginX, bottom: 16 },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const footerY = doc.internal.pageSize.getHeight() - 8;
    doc.setFontSize(7.5);
    doc.setFont("times", "italic");
    doc.setTextColor(70, 70, 70);
    doc.text(
      "Prepared through ETPB Legal CRM · Not a certified copy unless signed by an authorised officer.",
      marginX,
      footerY,
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - marginX, footerY, { align: "right" });
  }

  doc.save(`${payload.fileBaseName}.pdf`);
}
