/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ShellExternalIndexRouteImport } from './routes/_shell.external.index'
import { Route as ShellInternalIndexRouteImport } from './routes/_shell.internal.index'
import { Route as ShellExternalCourtIdCategoryRouteImport } from './routes/_shell.external.$courtId.$category'
import { Route as ShellInternalCourtIdCategoryRouteImport } from './routes/_shell.internal.$courtId.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExternalIndexRoute = ShellExternalIndexRouteImport.update({
  id: '/external/',
  path: '/external/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInternalIndexRoute = ShellInternalIndexRouteImport.update({
  id: '/internal/',
  path: '/internal/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExternalCourtIdCategoryRoute =
  ShellExternalCourtIdCategoryRouteImport.update({
    id: '/external/$courtId/$category',
    path: '/external/$courtId/$category',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellInternalCourtIdCategoryRoute =
  ShellInternalCourtIdCategoryRouteImport.update({
    id: '/internal/$courtId/$category',
    path: '/internal/$courtId/$category',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/notifications': typeof ShellNotificationsRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/external/': typeof ShellExternalIndexRoute
  '/internal/': typeof ShellInternalIndexRoute
  '/external/$courtId/$category': typeof ShellExternalCourtIdCategoryRoute
  '/internal/$courtId/$category': typeof ShellInternalCourtIdCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/notifications': typeof ShellNotificationsRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/external': typeof ShellExternalIndexRoute
  '/internal': typeof ShellInternalIndexRoute
  '/external/$courtId/$category': typeof ShellExternalCourtIdCategoryRoute
  '/internal/$courtId/$category': typeof ShellInternalCourtIdCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/external/': typeof ShellExternalIndexRoute
  '/_shell/internal/': typeof ShellInternalIndexRoute
  '/_shell/external/$courtId/$category': typeof ShellExternalCourtIdCategoryRoute
  '/_shell/internal/$courtId/$category': typeof ShellInternalCourtIdCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/external/'
    | '/internal/'
    | '/external/$courtId/$category'
    | '/internal/$courtId/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/external'
    | '/internal'
    | '/external/$courtId/$category'
    | '/internal/$courtId/$category'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/notifications'
    | '/_shell/settings'
    | '/_shell/users'
    | '/_shell/external/'
    | '/_shell/internal/'
    | '/_shell/external/$courtId/$category'
    | '/_shell/internal/$courtId/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/external/': {
      id: '/_shell/external/'
      path: '/external'
      fullPath: '/external/'
      preLoaderRoute: typeof ShellExternalIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/internal/': {
      id: '/_shell/internal/'
      path: '/internal'
      fullPath: '/internal/'
      preLoaderRoute: typeof ShellInternalIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/external/$courtId/$category': {
      id: '/_shell/external/$courtId/$category'
      path: '/external/$courtId/$category'
      fullPath: '/external/$courtId/$category'
      preLoaderRoute: typeof ShellExternalCourtIdCategoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/internal/$courtId/$category': {
      id: '/_shell/internal/$courtId/$category'
      path: '/internal/$courtId/$category'
      fullPath: '/internal/$courtId/$category'
      preLoaderRoute: typeof ShellInternalCourtIdCategoryRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellExternalIndexRoute: typeof ShellExternalIndexRoute
  ShellInternalIndexRoute: typeof ShellInternalIndexRoute
  ShellExternalCourtIdCategoryRoute: typeof ShellExternalCourtIdCategoryRoute
  ShellInternalCourtIdCategoryRoute: typeof ShellInternalCourtIdCategoryRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellExternalIndexRoute: ShellExternalIndexRoute,
  ShellInternalIndexRoute: ShellInternalIndexRoute,
  ShellExternalCourtIdCategoryRoute: ShellExternalCourtIdCategoryRoute,
  ShellInternalCourtIdCategoryRoute: ShellInternalCourtIdCategoryRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
